feat: Add calculator setup
ibukun53/JS-calculator pull request #1
Opened 2023-11-03 13:28 UTC by ibukun53

### Add Calculator Setup
The setup basically is to enhance the functionality of the web application by installing essential packages like yarn lint, prettier, yarn stylelint, yarn install and yarn eslint. This setup is specifically designed to tackle any bugs head-on and ensure smooth performance.

The main reason for this setup is the  optimizing the code and creating a seamless user experience.

2023-11-03 15:23 UTC, moshoodabdullahi requested changes
Nice work but take a look down here;
![image](https://github.com/ibukun53/calculator/assets/111710949/48c3b672-e554-4b52-a939-223eb06f9bbc)
I think it will be more helpful if you specify what type of calculator by adding Js to the name, it will give additional information that the calculator is built with Js

2023-11-03 15:23 UTC, moshoodabdullahi commented on index.html
> +    <title>Calculator</title>
Right here too you should have a Js before the calculator

2023-11-03 15:23 UTC, moshoodabdullahi commented on index.html
>    <body></body>
Right here, you should add an h1 element inside the body with maybe Hello World or something
You should also have the main element and give it role attribute and you should also link your js file too

2023-11-03 22:04 UTC, moshoodabdullahi requested changes
Let's start with the files, I should be able to see the files you will be working with, like 
Your JS file, your CSS file, README.md file, your LICENCE file, etc., and for this to be possible you need to make the necessary changes to these files like your name where it is expected and so on take this [link](https://github.com/moshoodabdullahi/js-calculator/pull/1) as a preference for your own setup

2023-11-03 22:07 UTC, moshoodabdullahi requested changes
![image](https://github.com/ibukun53/calculator/assets/111710949/0a8996c5-9fec-41d5-a795-ffddd59fad3d)
Take a look at this screenshot your setup should contain all that files

2023-11-04 23:43 UTC, teckcipher reviewed
Looks like we still have few more things to do. Please check my comments

2023-11-04 23:43 UTC, teckcipher commented on package.json
>    "name": "js-template",
Can we remove this name? or rename it to the name of this project?

2023-11-04 23:43 UTC, teckcipher commented on package.json
> +  },
Let's remove this too, since we are not using it for now.

2023-11-04 23:43 UTC, teckcipher commented on package.json
> +  "repository": "https://github.com/ibukun53/calculator.git",
I guess this repo is wrong

2023-11-04 23:43 UTC, teckcipher commented on README.md
There are other stuff in this readme that still need customization, take your time to read and go through it. Ideally, this readme should be well detailed with custom information rather than the template info.

2023-11-05 17:15 UTC, Yinkusadel requested changes
All that and you should be fine, Nice work so far

2023-11-05 17:15 UTC, Yinkusadel commented on README.md
> +- Linkedin: [@author](https://www.linkedin.com/ibukun53/)
for this how about replacing author with your name instead

2023-11-05 17:15 UTC, Yinkusadel commented on index.html
> +    <script src="js/index.js"></script>
Also i suggest you remove this for now and focus on the purpose of the PR ,you can implement that when js is needed for functionality, just like you'll create the utility class list file when you're about to work on design

2023-11-06 12:11 UTC, teckcipher approved these changes, later dismissed

2023-11-06 12:11 UTC, teckcipher commented on README.md
> +[Live Demo Link](https://deploy-preview-1--made-by-js-calculator.netlify.app/)
This should be your main deployment not your "deploy preview", thst is, https://made-by-js-calculator.netlify.app/, this url will be the one used on your master branch

2023-11-06 12:11 UTC, teckcipher commented on README.md
> +- Linkedin: [@author](https://www.linkedin.com/ibukun53/)
You didn't do this.

2023-11-06 12:52 UTC, ibukun53 commented on README.md
### ### ok

2023-11-06 13:04 UTC, teckcipher approved these changes

2023-11-06 13:39 UTC, Yinkusadel approved these changes
Nice 👍

2023-11-06 13:42 UTC, moshoodabdullahi approved these changes

2023-11-06 14:10 UTC, merged